
import { Pillar, Agent } from './types';

export const AGENTS: Record<string, Agent> = {
  PILLAR: {
    id: 'PILLAR',
    name: 'PILLAR',
    archetype: 'The Inner Architect',
    summary: 'Master your internal environment. Grounded, calm, and culturally fluent guidance for self-mastery.',
    systemPrompt: `You are The Inner Architect. You are grounded, calm, and culturally fluent. Your purpose is to help the user achieve self-mastery and life resilience. 
    Your responses MUST strictly follow this 3-step structure:
    1. A brief, insightful, and empathetic response to the user's input (max 3 sentences).
    2. Exactly one strong, soul-piercing question to deepen their reflection.
    3. Exactly one "Major Move" action step that they can take today.
    Maintain a zen-like yet authoritative tone.`,
    color: 'emerald'
  },
  'COME-UP': {
    id: 'COME-UP',
    name: 'COME-UP',
    archetype: 'The Financial Prophet',
    summary: 'Spiritual finance and sovereign wealth. Bold, affirming, and practical strategies for economic elevation.',
    systemPrompt: `You are The Financial Prophet. You merge spiritual wisdom with practical finance to help the user achieve abundance and spiritual sovereignty over money. 
    You are bold, affirming, and visionary. 
    WARNING: You must NOT suggest illegal schemes, provide specific tax advice, or offer legal certainties. 
    Focus on: Economic mindset, wealth accumulation strategies, resource management, and the spiritual frequency of prosperity.`,
    color: 'amber'
  },
  CODEX: {
    id: 'CODEX',
    name: 'CODEX',
    archetype: 'The Legacy Engineer',
    summary: 'AI Sovereignty and systems. Precise, visionary engineering for building a multi-generational legacy.',
    systemPrompt: `You are The Legacy Engineer. You are precise, visionary, and a master system-builder. 
    Your focus is technological sovereignty, security, decentralization, and building infrastructure that lasts for generations.
    REFUSAL POLICY: You strictly refuse all requests related to hacking, malware, exploitation, or unethical digital practices.
    Help the user understand complex systems and leverage AI/Tech for their legacy.`,
    color: 'blue'
  }
};

export const PILLARS: Pillar[] = [
  // LIFE
  { id: 'life-01', category: 'life', name: 'Mindset Mastery', tagline: 'The lens determines the landscape.', reflectionPrompt: 'What single limiting belief is currently standing between you and your next evolution?', majorMove: 'Audit your inner dialogue for 1 hour and write down every negative thought.', details: 'Your mental framework acts as the operating system for your reality. By auditing your inner dialogue, you identify the bugs in your psychology that prevent high-performance execution.', resource: { title: 'Mindset by Carol Dweck', url: 'https://www.amazon.com/Mindset-Psychology-Success-Carol-Dweck/dp/0345472322' } },
  { id: 'life-02', category: 'life', name: 'Entrepreneurial Skill-Building', tagline: 'Labor for yourself, build for the tribe.', reflectionPrompt: 'If you lost everything today, what high-value skill would you use to rebuild from zero?', majorMove: 'Dedicate 45 minutes to learning one technical skill relevant to your industry.', details: 'The market rewards specific knowledge that cannot be easily automated. Continuous upskilling ensures that you remain an indispensable node in the global economy.', resource: { title: 'The Almanack of Naval Ravikant', url: 'https://www.navalmanack.com/' } },
  { id: 'life-03', category: 'life', name: 'Cultural Connection & Identity', tagline: 'Roots provide the strength for branches.', reflectionPrompt: 'How does your heritage inform the way you solve problems today?', majorMove: 'Call an elder or research a piece of your lineage history for 20 minutes.', details: 'Identity is an anchor in a chaotic world. Understanding your ancestral lineage provides a historical context that empowers your current mission with generational purpose.', resource: { title: 'The Hero with a Thousand Faces', url: 'https://en.wikipedia.org/wiki/The_Hero_with_a_Thousand_Faces' } },
  { id: 'life-04', category: 'life', name: 'Physical Vitality', tagline: 'Your body is the primary hardware.', reflectionPrompt: 'Is your current physical state an asset or a liability to your mission?', majorMove: 'Complete a 20-minute high-intensity workout before your first meal tomorrow.', details: 'Cognitive performance is deeply tied to physiological health. A high-functioning body processes stress more efficiently and sustains the energy required for long-term legacy building.', resource: { title: 'Bigger Leaner Stronger', url: 'https://www.muscleforlife.com/bigger-leaner-stronger/' } },
  { id: 'life-05', category: 'life', name: 'Nutritional Resilience', tagline: 'Fuel, not just food.', reflectionPrompt: 'What are you consuming that is draining your cognitive clarity?', majorMove: 'Replace one processed snack today with a whole-food, plant-based alternative.', details: 'The chemical composition of your diet affects your mood and decision-making capabilities. Prioritizing nutrient density over convenience is a fundamental act of self-sovereignty.', resource: { title: 'How Not to Die', url: 'https://nutritionfacts.org/book/' } },
  { id: 'life-06', category: 'life', name: 'Digital Wealth Creation', tagline: 'Pixels into property.', reflectionPrompt: 'How can you transition from a digital consumer to a digital asset owner?', majorMove: 'Create one piece of digital content that provides genuine value to others.', details: 'The digital era allows for the creation of assets with near-zero marginal cost. Transforming consumption into creation is the key to escaping the time-for-money trap.', resource: { title: 'Show Your Work! by Austin Kleon', url: 'https://austinkleon.com/show-your-work/' } },
  { id: 'life-07', category: 'life', name: 'Community Connection', tagline: 'Your network is your safety net.', reflectionPrompt: 'Who in your circle is pushing you toward your highest self?', majorMove: 'Send a message of genuine appreciation to one mentor or peer today.', details: 'High-level success is a team sport. Cultivating deep, reciprocal relationships with other sovereigns creates a synergistic ecosystem that accelerates individual progress.', resource: { title: 'Give and Take by Adam Grant', url: 'https://www.adamgrant.net/book/give-and-take/' } },
  { id: 'life-08', category: 'life', name: 'Wisdom & Storytelling', tagline: 'Narratives shape reality.', reflectionPrompt: 'If your life was a myth, what chapter are you currently in?', majorMove: 'Write down the "Old Story" of your life and physically burn the paper.', details: 'Humanity operates on stories. Mastering the art of narrative allows you to frame your struggles as essential character development for your eventual victory.', resource: { title: 'Story by Robert McKee', url: 'https://mckeestory.com/' } },
  { id: 'life-09', category: 'life', name: 'Forgiveness & Gratitude', tagline: 'Release the weight to fly higher.', reflectionPrompt: 'Who are you holding a grudge against that is actually hurting your own progress?', majorMove: 'Write a letter of forgiveness (even if unsent) to someone who wronged you.', details: 'Resentment is a heavy energy that consumes cognitive bandwidth. Forgiveness is not for others; it is a tactical release of emotional baggage to regain speed.', resource: { title: 'The Book of Forgiving', url: 'https://www.amazon.com/Book-Forgiving-Fourfold-Healing-Ourselves/dp/0062203576' } },
  { id: 'life-10', category: 'life', name: 'Creative Expression', tagline: 'Art is the evidence of the soul.', reflectionPrompt: 'What creative urge have you been suppressing for the sake of "productivity"?', majorMove: 'Spend 15 minutes engaging in a creative hobby with no expectation of profit.', details: 'Creativity is the highest form of intelligence. Engaging in non-linear, expressive acts refreshes the mind and often reveals innovative solutions to logical problems.', resource: { title: 'The War of Art', url: 'https://stevenpressfield.com/books/the-war-of-art/' } },

  // MONEY
  { id: 'money-01', category: 'money', name: 'Measure', tagline: 'You cannot manage what you do not measure.', reflectionPrompt: 'Do you know exactly where every dollar went in the last 30 days?', majorMove: 'Download your last 3 months of bank statements and categorize every expense.', details: 'Financial clarity is the antidote to anxiety. Knowing your burn rate and cash flow is the first step toward moving from survival to strategic growth.', resource: { title: 'You Need A Budget (YNAB)', url: 'https://www.ynab.com/' } },
  { id: 'money-02', category: 'money', name: 'Think', tagline: 'Wealth is a thought form first.', reflectionPrompt: 'Do you view money as a scarce resource or a flow of energy?', majorMove: 'Sit in silence for 10 minutes and visualize your ideal financial state in detail.', details: 'Your relationship with wealth begins in the subconscious. Identifying and reprogramming "poverty consciousness" allows you to recognize opportunities previously hidden by fear.', resource: { title: 'Think and Grow Rich', url: 'https://en.wikipedia.org/wiki/Think_and_Grow_Rich' } },
  { id: 'money-03', category: 'money', name: 'Feel', tagline: 'Emotional intelligence governs financial outcomes.', reflectionPrompt: 'What emotion do you feel when you look at your bank balance?', majorMove: 'Identify one impulse purchase you made this week and trace the emotion behind it.', details: 'Most financial decisions are emotional responses disguised as logic. Mastering your emotional state prevents self-sabotage and allows for cold, rational capital allocation.', resource: { title: 'The Psychology of Money', url: 'https://www.morganhousel.com/books' } },
  { id: 'money-04', category: 'money', name: 'Speak', tagline: 'Language creates financial law.', reflectionPrompt: 'Do you say "I can\'t afford it" or "How can I afford it"?', majorMove: 'Correct yourself every time you use a scarcity-based phrase today.', details: 'The words you use reinforce your financial reality. Shifting from declarative scarcity to inquisitive abundance changes how your brain scans for solutions.', resource: { title: 'Rich Dad Poor Dad', url: 'https://www.richdad.com/' } },
  { id: 'money-05', category: 'money', name: 'Ask', tagline: 'Closed mouths don\'t get fed.', reflectionPrompt: 'When was the last time you negotiated a better deal for yourself?', majorMove: 'Ask for a discount or a better rate on one service you pay for monthly.', details: 'Negotiation is the fastest way to increase your net worth. The ability to ask for what you deserve—and defend your value—is a foundational wealth skill.', resource: { title: 'Never Split the Difference', url: 'https://www.blackswanltd.com/never-split-the-difference' } },
  { id: 'money-06', category: 'money', name: 'Hold', tagline: 'Retention is the foundation of wealth.', reflectionPrompt: 'Is your "lifestyle creep" eating your ability to save?', majorMove: 'Automate a transfer of at least 10% of your next check into a separate account.', details: 'It is not what you make, but what you keep. Wealth is built through the strategic gap between your income and your expenses, consistently invested over time.', resource: { title: 'The Richest Man in Babylon', url: 'https://en.wikipedia.org/wiki/The_Richest_Man_in_Babylon_(book)' } },
  { id: 'money-07', category: 'money', name: 'Use', tagline: 'Capital is a tool for impact.', reflectionPrompt: 'Are your dollars voting for the future you want to see?', majorMove: 'Research a local or minority-owned business and make your next purchase there.', details: 'Spending is a form of investment in the world you want to live in. Conscious consumption directs resources toward the communities and values you wish to empower.', resource: { title: 'Soul of Money', url: 'https://soulofmoney.org/' } },
  { id: 'money-08', category: 'money', name: 'Manifest', tagline: 'Bring the vision to the physical plane.', reflectionPrompt: 'What tangible steps are you taking to bring your dream to life?', majorMove: 'Open a dedicated high-yield savings account specifically for your "Big Vision".', details: 'Manifestation requires physical containers. By creating specific accounts and goals, you give your financial energy a clear destination and a structure to grow within.', resource: { title: 'The Millionaire Fastlane', url: 'https://www.mjdemarco.com/books/' } },
  { id: 'money-09', category: 'money', name: 'Attract', tagline: 'Become the person wealth seeks out.', reflectionPrompt: 'What value are you providing to the world that attracts resources?', majorMove: 'Improve one aspect of your professional presentation (LinkedIn, portfolio, etc.).', details: 'Money follows value. By refining your personal brand and increasing your perceived value, you make it easier for resources to find their way into your hands.', resource: { title: 'Influence by Robert Cialdini', url: 'https://www.influenceatwork.com/' } },
  { id: 'money-10', category: 'money', name: 'Enjoy', tagline: 'Abundance is meant to be tasted.', reflectionPrompt: 'Are you so busy building for tomorrow that you can\'t enjoy today?', majorMove: 'Treat yourself to one small, high-quality experience today without guilt.', details: 'The purpose of wealth is freedom and experience. Practicing "strategic enjoyment" prevents burnout and maintains the high-vibration state necessary for continued attraction.', resource: { title: 'Die With Zero', url: 'https://www.diewithzerobook.com/' } },

  // TECH
  { id: 'tech-01', category: 'tech', name: 'Diaspora Empowerment', tagline: 'Bridging the gap with bits and bytes.', reflectionPrompt: 'How can technology solve a specific problem in your community?', majorMove: 'Identify one open-source project or local tech group you can join.', details: 'Technology is the ultimate equalizer. For the diaspora, mastering digital tools provides a way to bypass traditional gatekeepers and build global economic bridges.', resource: { title: 'The Sovereign Individual', url: 'https://www.amazon.com/Sovereign-Individual-Mastering-Transition-Information/dp/0684832720' } },
  { id: 'tech-02', category: 'tech', name: 'Resilience Shift', tagline: 'Adapt or evaporate.', reflectionPrompt: 'How quickly can you pivot when a platform or tool you rely on disappears?', majorMove: 'Back up all your critical business data to an offline hard drive today.', details: 'In a digital world, data loss is a fatal blow. Resilience is built through redundancy and a "platform-agnostic" mindset that ensures your operations survive any single point of failure.', resource: { title: 'Antifragile by Nassim Taleb', url: 'https://en.wikipedia.org/wiki/Antifragile' } },
  { id: 'tech-03', category: 'tech', name: 'Gamified Education', tagline: 'Learning is the ultimate game.', reflectionPrompt: 'How can you turn your hardest task into a game you want to play?', majorMove: 'Set a timer for 25 minutes and "compete" to finish one major task.', details: 'Dopamine is a tool for learning. By structuring your education and work through game mechanics, you bypass procrastination and tap into deep flow states.', resource: { title: 'SuperBetter by Jane McGonigal', url: 'https://www.superbetter.com/' } },
  { id: 'tech-04', category: 'tech', name: 'Blockchain Sovereignty', tagline: 'Trustless systems for a truthful world.', reflectionPrompt: 'Do you own your assets, or does a bank own them?', majorMove: 'Set up a non-custodial digital wallet and learn how to store your own keys.', details: 'True ownership is impossible in centralized systems. Blockchain technology allows for the direct control of assets and identity without reliance on third-party intermediaries.', resource: { title: 'Bitcoin Whitepaper', url: 'https://bitcoin.org/bitcoin.pdf' } },
  { id: 'tech-05', category: 'tech', name: 'Collaboration Tech', tagline: 'The lone wolf dies, the pack survives.', reflectionPrompt: 'Which digital tools are you using to empower your team?', majorMove: 'Audit your communication stack (Slack, Discord, etc.) and remove one distraction.', details: 'The Information Age allows for hyper-efficient, asynchronous collaboration. Selecting the right tools determines the speed and quality of your collective legacy building.', resource: { title: 'Remote: Office Not Required', url: 'https://basecamp.com/books/remote' } },
  { id: 'tech-06', category: 'tech', name: 'Localized AI', tagline: 'Personal intelligence at scale.', reflectionPrompt: 'Are you using AI to save time, or is it just another distraction?', majorMove: 'Create one custom AI prompt template that automates a recurring task.', details: 'AI is a force multiplier. Localizing AI means training models on your specific context and data to create a "digital twin" that handles your complexity with your nuance.', resource: { title: 'The Coming Wave', url: 'https://www.thecomingwave.com/' } },
  { id: 'tech-07', category: 'tech', name: 'Holistic Tech Balance', tagline: 'Digital minimalism is a superpower.', reflectionPrompt: 'When was the last time you went 24 hours without a screen?', majorMove: 'Turn off all non-essential phone notifications for the next 4 hours.', details: 'Constant connectivity erodes focus. Mastering the "off switch" is essential for the deep work and original thinking required to build long-term legacy.', resource: { title: 'Digital Minimalism by Cal Newport', url: 'https://www.calnewport.com/books/digital-minimalism/' } },
  { id: 'tech-08', category: 'tech', name: 'Security & Compliance', tagline: 'The walls of your digital kingdom.', reflectionPrompt: 'Is your password "123456" or a cryptographic fortress?', majorMove: 'Enable Two-Factor Authentication (2FA) on your three most used accounts.', details: 'In the digital arena, security is your primary defense. Proper hygiene—from encryption to identity management—protects your reputation and your accumulated wealth.', resource: { title: 'Privacy, Security, and OSINT Podcast', url: 'https://inteltechniques.com/podcast.html' } },
  { id: 'tech-09', category: 'tech', name: 'Data Performance', tagline: 'Numbers don\'t lie, but they can hide.', reflectionPrompt: 'What key metric are you currently ignoring in your digital life?', majorMove: 'Create a simple spreadsheet to track one personal or business KPI weekly.', details: 'Data-driven decision making removes the guesswork from growth. Identifying your "North Star" metric allows you to optimize your systems for maximum legacy impact.', resource: { title: 'Measure What Matters', url: 'https://www.whatmatters.com/' } },
  { id: 'tech-10', category: 'tech', name: 'Legacy Systems', tagline: 'Code that outlives the coder.', reflectionPrompt: 'If you vanished tomorrow, how much of your digital work survives?', majorMove: 'Write a digital "In Case of Emergency" document for your loved ones.', details: 'Legacy is built on systems that endure. Engineering your digital infrastructure for long-term accessibility ensures that your impact continues beyond your physical presence.', resource: { title: 'The Long Now Foundation', url: 'https://longnow.org/' } },
];
